[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
version = "2.0.0"
name = "Markdown-SPA"
description = "A static site generator for Markdown files."
readme = "README.md"
authors = [{name = "MrSpaar"}]
keywords = ["markdown", "SPA", "SSG"]
license = {file = "LICENSE"}
requires-python = ">=3.8"
dependencies = ["markdown", "jinja2", "pygments", "click"]

[project.urls]
Documentation = "https://mrspaar.github.io/Markdown-SPA/"
Source = "https://github.com/MrSpaar/Markdown-SPA"
Issues = "https://github.com/MrSpaar/Markdown-SPA/issues"

[project.scripts]
markdown_spa = "markdown_spa:main"
